/*
import { americanOnly } from '../translations/american-only.js';
import { britishOnly } from '../translations/british-only.js';
import { americanToBritishSpelling } from '../translations/american-to-british-spelling.js';
import { americanToBritishTitles } from '../translations/american-to-british-titles.js';
*/

/*
let textBox = document.getElementById("text-input")
let translateButton = document.getElementById('translate-btn');
let clearButton = document.getElementById('clear-btn');
let locale = document.getElementById("locale-select");
let outputDiv = document.getElementById("translated-sentence");
let errorDiv = document.getElementById("error-msg");

const americanOnly = {
    "acclimate": "acclimatise",
    "acetaminophen": "paracetamol",
    "baby carriage": "pram",
    "backhoe": "digger",
    "band-aid": "Elastoplast",
    "bangs": "fringe",
    "barrette": "hair slide",
    "baseboard": "skirting board",
    "bedroom community": "dormitory town",
    "blacktop": "tarmac",
    "bleachers": "stands",
    "blinders": "blinkers",
    "blood sausage": "black pudding",
    "boardwalk": "promenade",
    "bobby pin": "Kirby grip",
    "booger": "bogey",
    "bookmobile": "mobile library",
    "breadbox": "bread bin",
    "bullhorn": "loudhailer",
    "burglarize": "burgle",
    "burlap": "hessian",
    "canadian bacon": "back bacon",
    "candy apple": "toffee apple",
    "candied apple": "toffee apple",
    "careen": "career",
    "catsup": "ketchup",
    "cell phone": "mobile",
    "cellphone": "mobile",
    "certified mail": "recorded delivery",
    "chapstick": "lip balm",
    "charge account": "credit account",
    "checkers": "draughts",
    "checking account": "current account",
    "cilantro": "coriander",
    "cleats": "football boots",
    "condo": "flat",
    "costume party": "fancy-dress party",
    "cotton candy": "candy floss",
    "counterclockwise": "anti-clockwise",
    "coveralls": "overalls",
    "diaper": "nappy",
    "discombobulated": "discomposed",
    "dish towel": "tea towel",
    "dishrag": "dishcloth",
    "dish soap": "washing-up liquid",
    "dishwashing liquid": "washing-up liquid",
    "district attorney": "Crown Prosecutor",
    "divided highway": "dual carriageway",
    "doohickey": "wotsit",
    "downspout": "drainpipe",
    "drape": "curtain",
    "drapes": "curtain",
    "driver license": "driving licence",
    "driver's license": "driving licence",
    "drugstore": "chemist",
    "drywall": "plasterboard",
    "dumpster": "skip",
    "eggplant": "aubergine",
    "emergency brake": "handbrake",
    "eminent domain": "compulsory purchase",
    "envision": "to envisage",
    "eraser": "rubber",
    "expressway": "motorway",
    "fanny pack": "bum bag",
    "faucet": "tap",
    "flashlight": "torch",
    "flatware": "cutlery",
    "freeway": "motorway",
    "fries": "chips",
    "french fries": "chips",
    "french press": "cafetière",
    "freshman": "fresher",
    "front desk": "reception",
    "frosting": "icing",
    "garbage can": "dustbin",
    "gasoline": "petrol",
    "general delivery": "poste restante",
    "grifter": "con man",
    "ground beef": "mince",
    "grunt": "squaddie",
    "hard candy": "boiled sweets",
    "heavy cream": "double cream",
    "jackhammer": "pneumatic drill",
    "jell-o": "jelly",
    "ladybug": "ladybird",
    "laundromat": "laundrette",
    "learner's permit": "provisional driving licence",
    "license plate": "number plate",
    "license tag": "number plate",
    "mail carrier": "postal worker",
    "mailman": "postman",
    "main street": "high street",
    "mama": "mam",
    "mamma": "mam",
    "momma": "mam",
    "mom": "mum",
    "mass transit": "public transport",
    "math": "maths",
    "mohawk": "mohican",
    "mortician": "undertaker",
    "narc": "grass",
    "nightcrawler": "earthworm",
    "nightstick": "truncheon",
    "nix": "cancel",
    "obligated": "obliged",
    "off-the-rack": "off-the-peg",
    "oftentimes": "often",
    "overpass": "flyover",
    "pantyhose": "tights",
    "paper route": "paper round",
    "parking garage": "car park",
    "parking lot": "car park",
    "penitentiary": "prison",
    "plastic wrap": "cling-film",
    "play hooky": "bunk off",
    "plexiglas": "Perspex",
    "popsicle": "ice lolly",
    "powdered sugar": "icing sugar",
    "pre-authorized payment": "direct debit",
    "pre-authorized withdrawal": "direct debit",
    "public holiday": "bank holiday",
    "rappel": "abseil",
    "realtor": "estate agent",
    "rif": "redundancy",
    "rif'd": "made redundant",
    "rowhouse": "terraced house",
    "rube goldberg device": "Heath Robinson device",
    "rube goldberg machine": "Heath Robinson device",
    "rugola": "rocket",
    "rutabaga": "swede",
    "rv": "caravan",
    "rv park": "caravan site",
    "saran wrap": "cling film",
    "scads": "great amounts",
    "scallion": "spring onion",
    "scalper": "ticket tout",
    "scotch tape": "Sellotape",
    "scuttlebutt": "rumour",
    "sedan automobile": "saloon",
    "self-rising flour": "self-raising flour",
    "shredded cheese": "grated cheese",
    "sidewalk": "pavement",
    "skim milk": "skimmed milk",
    "sneaker": "trainer",
    "sneakers": "trainers",
    "snuck": "sneaked",
    "soccer": "football",
    "soda pop": "soft drink",
    "specialty": "speciality",
    "spelunking": "caving",
    "spring break": "Easter holiday",
    "station wagon": "estate car",
    "steam shovel": "digger",
    "stickshift": "gear stick",
    "stool pigeon": "grass",
    "stoolie": "grass",
    "stop light": "traffic light",
    "streetcar": "tram",
    "stroller": "pram",
    "swap meet": "car boot sale",
    "sweatpants": "track bottoms",
    "tailpipe": "exhaust pipe",
    "takeout": "takeaway",
    "teleprompter": "compare autocue",
    "thumbtack": "drawing pin",
    "track meet": "athletics meeting",
    "trash": "rubbish",
    "trashcan": "bin",
    "travel trailer": "caravan",
    "turn signal": "turn-indicators",
    "tylenol": "paracetamol",
    "upscale": "upmarket",
    "vacationer": "holidaymaker",
    "vacay": "hols",
    "variety meats": "offal",
    "varmint": "vermin",
    "varmit": "vermin",
    "wastebasket": "wastepaper basket",
    "windshield": "windscreen",
    "yellow light": "amber",
    "zip code": "postcode",
    "zipper": "zip",
    "zucchini": "courgette"
}

const americanToBritishSpelling = {
    "accessorize": "accessorise",
    "accessorized": "accessorised",
    "accessorizes": "accessorises",
    "accessorizing": "accessorising",
    "acclimatization": "acclimatisation",
    "acclimatize": "acclimatise",
    "acclimatized": "acclimatised",
    "acclimatizes": "acclimatises",
    "acclimatizing": "acclimatising",
    "accouterments": "accoutrements",
    "eon": "aeon",
    "eons": "aeons",
    "aerogram": "aerogramme",
    "aerograms": "aerogrammes",
    "airplane": "aeroplane",
    "airplanes": "aeroplanes",
    "etiology": "aetiology",
    "aging": "ageing",
    "aggrandizement": "aggrandisement",
    "agonize": "agonise",
    "agonized": "agonised",
    "agonizes": "agonises",
    "agonizing": "agonising",
    "agonizingly": "agonisingly",
    "almanac": "almanack",
    "almanacs": "almanacks",
    "aluminum": "aluminium",
    "amortizable": "amortisable",
    "amortization": "amortisation",
    "amortizations": "amortisations",
    "amortize": "amortise",
    "amortized": "amortised",
    "amortizes": "amortises",
    "amortizing": "amortising",
    "amphitheater": "amphitheatre",
    "amphitheaters": "amphitheatres",
    "anemia": "anaemia",
    "anemic": "anaemic",
    "anesthesia": "anaesthesia",
    "anesthetic": "anaesthetic",
    "anesthetics": "anaesthetics",
    "anesthetize": "anaesthetize",
    "anesthetized": "anaesthetized",
    "anesthetizes": "anaesthetizes",
    "anesthetizing": "anaesthetizing",
    "anesthetist": "anaesthetist",
    "anesthetists": "anaesthetists",
    "analog": "analogue",
    "analogs": "analogues",
    "analyze": "analyse",
    "analyzed": "analysed",
    "analyzes": "analyses",
    "analyzing": "analysing",
    "anglicize": "anglicise",
    "anglicized": "anglicised",
    "anglicizes": "anglicises",
    "anglicizing": "anglicising",
    "annualized": "annualised",
    "antagonize": "antagonise",
    "antagonized": "antagonised",
    "antagonizes": "antagonises",
    "antagonizing": "antagonising",
    "apologize": "apologise",
    "apologized": "apologised",
    "apologizes": "apologises",
    "apologizing": "apologising",
    "appall": "appal",
    "appalls": "appals",
    "appetizer": "appetiser",
    "appetizers": "appetisers",
    "appetizing": "appetising",
    "appetizingly": "appetisingly",
    "arbor": "arbour",
    "arbors": "arbours",
    "archeological": "archaeological",
    "archeologically": "archaeologically",
    "archeologist": "archaeologist",
    "archeologists": "archaeologists",
    "archeology": "archaeology",
    "ardor": "ardour",
    "armor": "armour",
    "armored": "armoured",
    "armorer": "armourer",
    "armorers": "armourers",
    "armories": "armouries",
    "armory": "armoury",
    "artifact": "artefact",
    "artifacts": "artefacts",
    "authorize": "authorise",
    "authorized": "authorised",
    "authorizes": "authorises",
    "authorizing": "authorising",
    "ax": "axe",
    "backpedaled": "backpedalled",
    "backpedaling": "backpedalling",
    "banister": "bannister",
    "banisters": "bannisters",
    "baptize": "baptise",
    "baptized": "baptised",
    "baptizes": "baptises",
    "baptizing": "baptising",
    "battleax": "battleaxe",
    "balk": "baulk",
    "balked": "baulked",
    "balking": "baulking",
    "balks": "baulks",
    "bedeviled": "bedevilled",
    "bedeviling": "bedevilling",
    "behavior": "behaviour",
    "behavioral": "behavioural",
    "behaviorism": "behaviourism",
    "behaviorist": "behaviourist",
    "behaviorists": "behaviourists",
    "behaviors": "behaviours",
    "behoove": "behove",
    "behooved": "behoved",
    "behooves": "behoves",
    "bejeweled": "bejewelled",
    "belabor": "belabour",
    "belabored": "belaboured",
    "belaboring": "belabouring",
    "belabors": "belabours",
    "beveled": "bevelled",
    "bevies": "bevvies",
    "bevy": "bevvy",
    "biased": "biassed",
    "biasing": "biassing",
    "binging": "bingeing",
    "bougainvillea": "bougainvillaea",
    "bougainvilleas": "bougainvillaeas",
    "bowdlerize": "bowdlerise",
    "bowdlerized": "bowdlerised",
    "bowdlerizes": "bowdlerises",
    "bowdlerizing": "bowdlerising",
    "breathalyze": "breathalyse",
    "breathalyzed": "breathalysed",
    "breathalyzer": "breathalyser",
    "breathalyzers": "breathalysers",
    "breathalyzes": "breathalyses",
    "breathalyzing": "breathalysing",
    "brutalize": "brutalise",
    "brutalized": "brutalised",
    "brutalizes": "brutalises",
    "brutalizing": "brutalising",
    "busses": "buses",
    "bussing": "busing",
    "cesarean": "caesarean",
    "cesareans": "caesareans",
    "caliber": "calibre",
    "calibers": "calibres",
    "caliper": "calliper",
    "calipers": "callipers",
    "calisthenics": "callisthenics",
    "canalize": "canalise",
    "canalized": "canalised",
    "canalizes": "canalises",
    "canalizing": "canalising",
    "canceled": "cancelled",
    "canceling": "cancelling",
    "candor": "candour",
    "cannibalize": "cannibalise",
    "cannibalized": "cannibalised",
    "cannibalizes": "cannibalises",
    "cannibalizing": "cannibalising",
    "canonize": "canonise",
    "canonized": "canonised",
    "canonizes": "canonises",
    "canonizing": "canonising",
    "capitalize": "capitalise",
    "capitalized": "capitalised",
    "capitalizes": "capitalises",
    "capitalizing": "capitalising",
    "caramelize": "caramelise",
    "caramelized": "caramelised",
    "caramelizes": "caramelises",
    "caramelizing": "caramelising",
    "carbonize": "carbonise",
    "carbonized": "carbonised",
    "carbonizes": "carbonises",
    "carbonizing": "carbonising",
    "caroled": "carolled",
    "caroling": "carolling",
    "catalog": "catalogue",
    "cataloged": "catalogued",
    "catalogs": "catalogues",
    "cataloging": "cataloguing",
    "catalyze": "catalyse",
    "catalyzed": "catalysed",
    "catalyzes": "catalyses",
    "catalyzing": "catalysing",
    "categorize": "categorise",
    "categorized": "categorised",
    "categorizes": "categorises",
    "categorizing": "categorising",
    "cauterize": "cauterise",
    "cauterized": "cauterised",
    "cauterizes": "cauterises",
    "cauterizing": "cauterising",
    "caviled": "cavilled",
    "caviling": "cavilling",
    "centigram": "centigramme",
    "centigrams": "centigrammes",
    "centiliter": "centilitre",
    "centiliters": "centilitres",
    "centimeter": "centimetre",
    "centimeters": "centimetres",
    "centralize": "centralise",
    "centralized": "centralised",
    "centralizes": "centralises",
    "centralizing": "centralising",
    "center": "centre",
    "centered": "centred",
    "centerfold": "centrefold",
    "centerfolds": "centrefolds",
    "centerpiece": "centrepiece",
    "centerpieces": "centrepieces",
    "centers": "centres",
    "channeled": "channelled",
    "channeling": "channelling",
    "characterize": "characterise",
    "characterized": "characterised",
    "characterizes": "characterises",
    "characterizing": "characterising",
    "check": "cheque",
    "checkbook": "chequebook",
    "checkbooks": "chequebooks",
    "checkered": "chequered",
    "checks": "cheques",
    "chili": "chilli",
    "chimera": "chimaera",
    "chimeras": "chimaeras",
    "chiseled": "chiselled",
    "chiseling": "chiselling",
    "circularize": "circularise",
    "circularized": "circularised",
    "circularizes": "circularises",
    "circularizing": "circularising",
    "civilize": "civilise",
    "civilized": "civilised",
    "civilizes": "civilises",
    "civilizing": "civilising",
    "clamor": "clamour",
    "clamored": "clamoured",
    "clamoring": "clamouring",
    "clamors": "clamours",
    "clangor": "clangour",
    "clarinetist": "clarinettist",
    "clarinetists": "clarinettists",
    "collectivize": "collectivise",
    "collectivized": "collectivised",
    "collectivizes": "collectivises",
    "collectivizing": "collectivising",
    "colonization": "colonisation",
    "colonize": "colonise",
    "colonized": "colonised",
    "colonizer": "coloniser",
    "colonizers": "colonisers",
    "colonizes": "colonises",
    "colonizing": "colonising",
    "color": "colour",
    "colorant": "colourant",
    "colorants": "colourants",
    "colored": "coloured",
    "coloreds": "coloureds",
    "colorful": "colourful",
    "colorfully": "colourfully",
    "coloring": "colouring",
    "colorize": "colourize",
    "colorized": "colourized",
    "colorizes": "colourizes",
    "colorizing": "colourizing",
    "colorless": "colourless",
    "colors": "colours",
    "commercialize": "commercialise",
    "commercialized": "commercialised",
    "commercializes": "commercialises",
    "commercializing": "commercialising",
    "compartmentalize": "compartmentalise",
    "compartmentalized": "compartmentalised",
    "compartmentalizes": "compartmentalises",
    "compartmentalizing": "compartmentalising",
    "computerize": "computerise",
    "computerized": "computerised",
    "computerizes": "computerises",
    "computerizing": "computerising",
    "conceptualize": "conceptualise",
    "conceptualized": "conceptualised",
    "conceptualizes": "conceptualises",
    "conceptualizing": "conceptualising",
    "connection": "connexion",
    "connections": "connexions",
    "contextualize": "contextualise",
    "contextualized": "contextualised",
    "contextualizes": "contextualises",
    "contextualizing": "contextualising",
    "cozier": "cosier",
    "cozies": "cosies",
    "coziest": "cosiest",
    "cozily": "cosily",
    "coziness": "cosiness",
    "cozy": "cosy",
    "councilor": "councillor",
    "councilors": "councillors",
    "counseled": "counselled",
    "counseling": "counselling",
    "counselor": "counsellor",
    "counselors": "counsellors",
    "crenelated": "crenellated",
    "criminalize": "criminalise",
    "criminalized": "criminalised",
    "criminalizes": "criminalises",
    "criminalizing": "criminalising",
    "criticize": "criticise",
    "criticized": "criticised",
    "criticizes": "criticises",
    "criticizing": "criticising",
    "crueler": "crueller",
    "cruelest": "cruellest",
    "crystallization": "crystallisation",
    "crystallize": "crystallise",
    "crystallized": "crystallised",
    "crystallizes": "crystallises",
    "crystallizing": "crystallising",
    "cudgeled": "cudgelled",
    "cudgeling": "cudgelling",
    "customize": "customise",
    "customized": "customised",
    "customizes": "customises",
    "customizing": "customising",
    "cipher": "cypher",
    "ciphers": "cyphers",
    "decentralization": "decentralisation",
    "decentralize": "decentralise",
    "decentralized": "decentralised",
    "decentralizes": "decentralises",
    "decentralizing": "decentralising",
    "decriminalization": "decriminalisation",
    "decriminalize": "decriminalise",
    "decriminalized": "decriminalised",
    "decriminalizes": "decriminalises",
    "decriminalizing": "decriminalising",
    "defense": "defence",
    "defenseless": "defenceless",
    "defenses": "defences",
    "dehumanization": "dehumanisation",
    "dehumanize": "dehumanise",
    "dehumanized": "dehumanised",
    "dehumanizes": "dehumanises",
    "dehumanizing": "dehumanising",
    "demeanor": "demeanour",
    "demilitarization": "demilitarisation",
    "demilitarize": "demilitarise",
    "demilitarized": "demilitarised",
    "demilitarizes": "demilitarises",
    "demilitarizing": "demilitarising",
    "demobilization": "demobilisation",
    "demobilize": "demobilise",
    "demobilized": "demobilised",
    "demobilizes": "demobilises",
    "demobilizing": "demobilising",
    "democratization": "democratisation",
    "democratize": "democratise",
    "democratized": "democratised",
    "democratizes": "democratises",
    "democratizing": "democratising",
    "demonize": "demonise",
    "demonized": "demonised",
    "demonizes": "demonises",
    "demonizing": "demonising",
    "demoralization": "demoralisation",
    "demoralize": "demoralise",
    "demoralized": "demoralised",
    "demoralizes": "demoralises",
    "demoralizing": "demoralising",
    "denationalization": "denationalisation",
    "denationalize": "denationalise",
    "denationalized": "denationalised",
    "denationalizes": "denationalises",
    "denationalizing": "denationalising",
    "donut": "doughnut",
    "deodorize": "deodorise",
    "deodorized": "deodorised",
    "deodorizes": "deodorises",
    "deodorizing": "deodorising",
    "depersonalize": "depersonalise",
    "depersonalized": "depersonalised",
    "depersonalizes": "depersonalises",
    "depersonalizing": "depersonalising",
    "deputize": "deputise",
    "deputized": "deputised",
    "deputizes": "deputises",
    "deputizing": "deputising",
    "desensitization": "desensitisation",
    "desensitize": "desensitise",
    "desensitized": "desensitised",
    "desensitizes": "desensitises",
    "desensitizing": "desensitising",
    "destabilization": "destabilisation",
    "destabilize": "destabilise",
    "destabilized": "destabilised",
    "destabilizes": "destabilises",
    "destabilizing": "destabilising",
    "dialed": "dialled",
    "dialing": "dialling",
    "dialog": "dialogue",
    "dialogs": "dialogues",
    "diarrhea": "diarrhoea",
    "digitize": "digitise",
    "digitized": "digitised",
    "digitizes": "digitises",
    "digitizing": "digitising",
    "disk": "disc",
    "discolor": "discolour",
    "discolored": "discoloured",
    "discoloring": "discolouring",
    "discolors": "discolours",
    "disks": "discs",
    "disemboweled": "disembowelled",
    "disemboweling": "disembowelling",
    "disfavor": "disfavour",
    "disheveled": "dishevelled",
    "dishonor": "dishonour",
    "dishonorable": "dishonourable",
    "dishonorably": "dishonourably",
    "dishonored": "dishonoured",
    "dishonoring": "dishonouring",
    "dishonors": "dishonours",
    "disorganization": "disorganisation",
    "disorganized": "disorganised",
    "distill": "distil",
    "distills": "distils",
    "dramatization": "dramatisation",
    "dramatizations": "dramatisations",
    "dramatize": "dramatise",
    "dramatized": "dramatised",
    "dramatizes": "dramatises",
    "dramatizing": "dramatising",
    "draft": "draught",
    "draftboard": "draughtboard",
    "draftboards": "draughtboards",
    "draftier": "draughtier",
    "draftiest": "draughtiest",
    "drafts": "draughts",
    "draftsman": "draughtsman",
    "draftsmanship": "draughtsmanship",
    "draftsmen": "draughtsmen",
    "draftswoman": "draughtswoman",
    "draftswomen": "draughtswomen",
    "drafty": "draughty",
    "driveled": "drivelled",
    "driveling": "drivelling",
    "dueled": "duelled",
    "dueling": "duelling",
    "economize": "economise",
    "economized": "economised",
    "economizes": "economises",
    "economizing": "economising",
    "edema": "edoema",
    "editorialize": "editorialise",
    "editorialized": "editorialised",
    "editorializes": "editorialises",
    "editorializing": "editorialising",
    "empathize": "empathise",
    "empathized": "empathised",
    "empathizes": "empathises",
    "empathizing": "empathising",
    "emphasize": "emphasise",
    "emphasized": "emphasised",
    "emphasizes": "emphasises",
    "emphasizing": "emphasising",
    "enameled": "enamelled",
    "enameling": "enamelling",
    "enamored": "enamoured",
    "encyclopedia": "encyclopaedia",
    "encyclopedias": "encyclopaedias",
    "encyclopedic": "encyclopaedic",
    "endeavor": "endeavour",
    "endeavored": "endeavoured",
    "endeavoring": "endeavouring",
    "endeavors": "endeavours",
    "energize": "energise",
    "energized": "energised",
    "energizes": "energises",
    "energizing": "energising",
    "enroll": "enrol",
    "enrolls": "enrols",
    "enthrall": "enthral",
    "enthralls": "enthrals",
    "epaulet": "epaulette",
    "epaulets": "epaulettes",
    "epicenter": "epicentre",
    "epicenters": "epicentres",
    "epilog": "epilogue",
    "epilogs": "epilogues",
    "epitomize": "epitomise",
    "epitomized": "epitomised",
    "epitomizes": "epitomises",
    "epitomizing": "epitomising",
    "equalization": "equalisation",
    "equalize": "equalise",
    "equalized": "equalised",
    "equalizer": "equaliser",
    "equalizers": "equalisers",
    "equalizes": "equalises",
    "equalizing": "equalising",
    "eulogize": "eulogise",
    "eulogized": "eulogised",
    "eulogizes": "eulogises",
    "eulogizing": "eulogising",
    "evangelize": "evangelise",
    "evangelized": "evangelised",
    "evangelizes": "evangelises",
    "evangelizing": "evangelising",
    "exorcize": "exorcise",
    "exorcized": "exorcised",
    "exorcizes": "exorcises",
    "exorcizing": "exorcising",
    "extemporization": "extemporisation",
    "extemporize": "extemporise",
    "extemporized": "extemporised",
    "extemporizes": "extemporises",
    "extemporizing": "extemporising",
    "externalization": "externalisation",
    "externalizations": "externalisations",
    "externalize": "externalise",
    "externalized": "externalised",
    "externalizes": "externalises",
    "externalizing": "externalising",
    "factorize": "factorise",
    "factorized": "factorised",
    "factorizes": "factorises",
    "factorizing": "factorising",
    "fecal": "faecal",
    "feces": "faeces",
    "familiarization": "familiarisation",
    "familiarize": "familiarise",
    "familiarized": "familiarised",
    "familiarizes": "familiarises",
    "familiarizing": "familiarising",
    "fantasize": "fantasise",
    "fantasized": "fantasised",
    "fantasizes": "fantasises",
    "fantasizing": "fantasising",
    "favorable": "favourable",
    "favorably": "favourably",
    "favored": "favoured",
    "favoring": "favouring",
    "favorite": "favourite",
    "favorites": "favourites",
    "favoritism": "favouritism",
    "favor": "favour",
    "favors": "favours",
    "feminize": "feminise",
    "feminized": "feminised",
    "feminizes": "feminises",
    "feminizing": "feminising",
    "fertilization": "fertilisation",
    "fertilize": "fertilise",
    "fertilized": "fertilised",
    "fertilizer": "fertiliser",
    "fertilizers": "fertilisers",
    "fertilizes": "fertilises",
    "fertilizing": "fertilising",
    "fervor": "fervour",
    "fiber": "fibre",
    "fiberglass": "fibreglass",
    "fibers": "fibres",
    "fictionalization": "fictionalisation",
    "fictionalizations": "fictionalisations",
    "fictionalize": "fictionalise",
    "fictionalized": "fictionalised",
    "fictionalizes": "fictionalises",
    "fictionalizing": "fictionalising",
    "filet": "fillet",
    "fileted": "filleted",
    "fileting": "filleting",
    "filets": "fillets",
    "finalization": "finalisation",
    "finalize": "finalise",
    "finalized": "finalised",
    "finalizes": "finalises",
    "finalizing": "finalising",
    "flutist": "flautist",
    "flutists": "flautists",
    "flavor": "flavour",
    "flavored": "flavoured",
    "flavoring": "flavouring",
    "flavorings": "flavourings",
    "flavorless": "flavourless",
    "flavors": "flavours",
    "flavorsome": "flavoursome",
    "fetal": "foetal",
    "fetid": "foetid",
    "fetus": "foetus",
    "fetuses": "foetuses",
    "formalization": "formalisation",
    "formalize": "formalise",
    "formalized": "formalised",
    "formalizes": "formalises",
    "formalizing": "formalising",
    "fossilization": "fossilisation",
    "fossilize": "fossilise",
    "fossilized": "fossilised",
    "fossilizes": "fossilises",
    "fossilizing": "fossilising",
    "fraternization": "fraternisation",
    "fraternize": "fraternise",
    "fraternized": "fraternised",
    "fraternizes": "fraternises",
    "fraternizing": "fraternising",
    "fulfill": "fulfil",
    "fulfillment": "fulfilment",
    "fulfills": "fulfils",
    "funneled": "funnelled",
    "funneling": "funnelling",
    "galvanize": "galvanise",
    "galvanized": "galvanised",
    "galvanizes": "galvanises",
    "galvanizing": "galvanising",
    "gamboled": "gambolled",
    "gamboling": "gambolling",
    "jail": "gaol",
    "jailbird": "gaolbird",
    "jailbirds": "gaolbirds",
    "jailbreak": "gaolbreak",
    "jailbreaks": "gaolbreaks",
    "jailed": "gaoled",
    "jailer": "gaoler",
    "jailers": "gaolers",
    "jailing": "gaoling",
    "jails": "gaols",
    "gasses": "gases",
    "gage": "gauge",
    "gaged": "gauged",
    "gages": "gauges",
    "gaging": "gauging",
    "generalization": "generalisation",
    "generalizations": "generalisations",
    "generalize": "generalise",
    "generalized": "generalised",
    "generalizes": "generalises",
    "generalizing": "generalising",
    "gypsies": "gipsies",
    "glamorize": "glamorise",
    "glamorized": "glamorised",
    "glamorizes": "glamorises",
    "glamorizing": "glamorising",
    "glamor": "glamour",
    "globalization": "globalisation",
    "globalize": "globalise",
    "globalized": "globalised",
    "globalizes": "globalises",
    "globalizing": "globalising",
    "gluing": "glueing",
    "goiter": "goitre",
    "goiters": "goitres",
    "gonorrhea": "gonorrhoea",
    "gram": "gramme",
    "grams": "grammes",
    "graveled": "gravelled",
    "gray": "grey",
    "grayed": "greyed",
    "graying": "greying",
    "grayish": "greyish",
    "grayness": "greyness",
    "grays": "greys",
    "groveled": "grovelled",
    "groveling": "grovelling",
    "groin": "groyne",
    "groins": "groynes",
    "grueling": "gruelling",
    "gruelingly": "gruellingly",
    "griffin": "gryphon",
    "griffins": "gryphons",
    "gynecological": "gynaecological",
    "gynecologist": "gynaecologist",
    "gynecologists": "gynaecologists",
    "gynecology": "gynaecology",
    "hematological": "haematological",
    "hematologist": "haematologist",
    "hematologists": "haematologists",
    "hematology": "haematology",
    "hemoglobin": "haemoglobin",
    "hemophilia": "haemophilia",
    "hemophiliac": "haemophiliac",
    "hemophiliacs": "haemophiliacs",
    "hemorrhage": "haemorrhage",
    "hemorrhaged": "haemorrhaged",
    "hemorrhages": "haemorrhages",
    "hemorrhaging": "haemorrhaging",
    "hemorrhoids": "haemorrhoids",
    "harbor": "harbour",
    "harbored": "harboured",
    "harboring": "harbouring",
    "harbors": "harbours",
    "harmonization": "harmonisation",
    "harmonize": "harmonise",
    "harmonized": "harmonised",
    "harmonizes": "harmonises",
    "harmonizing": "harmonising",
    "homeopath": "homoeopath",
    "homeopathic": "homoeopathic",
    "homeopaths": "homoeopaths",
    "homeopathy": "homoeopathy",
    "homogenize": "homogenise",
    "homogenized": "homogenised",
    "homogenizes": "homogenises",
    "homogenizing": "homogenising",
    "honor": "honour",
    "honorable": "honourable",
    "honorably": "honourably",
    "honored": "honoured",
    "honoring": "honouring",
    "honors": "honours",
    "hospitalization": "hospitalisation",
    "hospitalize": "hospitalise",
    "hospitalized": "hospitalised",
    "hospitalizes": "hospitalises",
    "hospitalizing": "hospitalising",
    "humanize": "humanise",
    "humanized": "humanised",
    "humanizes": "humanises",
    "humanizing": "humanising",
    "humor": "humour",
    "humored": "humoured",
    "humoring": "humouring",
    "humorless": "humourless",
    "humors": "humours",
    "hybridize": "hybridise",
    "hybridized": "hybridised",
    "hybridizes": "hybridises",
    "hybridizing": "hybridising",
    "hypnotize": "hypnotise",
    "hypnotized": "hypnotised",
    "hypnotizes": "hypnotises",
    "hypnotizing": "hypnotising",
    "hypothesize": "hypothesise",
    "hypothesized": "hypothesised",
    "hypothesizes": "hypothesises",
    "hypothesizing": "hypothesising",
    "idealization": "idealisation",
    "idealize": "idealise",
    "idealized": "idealised",
    "idealizes": "idealises",
    "idealizing": "idealising",
    "idolize": "idolise",
    "idolized": "idolised",
    "idolizes": "idolises",
    "idolizing": "idolising",
    "immobilization": "immobilisation",
    "immobilize": "immobilise",
    "immobilized": "immobilised",
    "immobilizer": "immobiliser",
    "immobilizers": "immobilisers",
    "immobilizes": "immobilises",
    "immobilizing": "immobilising",
    "immortalize": "immortalise",
    "immortalized": "immortalised",
    "immortalizes": "immortalises",
    "immortalizing": "immortalising",
    "immunization": "immunisation",
    "immunize": "immunise",
    "immunized": "immunised",
    "immunizes": "immunises",
    "immunizing": "immunising",
    "impaneled": "impanelled",
    "impaneling": "impanelling",
    "imperiled": "imperilled",
    "imperiling": "imperilling",
    "individualize": "individualise",
    "individualized": "individualised",
    "individualizes": "individualises",
    "individualizing": "individualising",
    "industrialize": "industrialise",
    "industrialized": "industrialised",
    "industrializes": "industrialises",
    "industrializing": "industrialising",
    "inflection": "inflexion",
    "inflections": "inflexions",
    "initialize": "initialise",
    "initialized": "initialised",
    "initializes": "initialises",
    "initializing": "initialising",
    "initialed": "initialled",
    "initialing": "initialling",
    "install": "instal",
    "installment": "instalment",
    "installments": "instalments",
    "installs": "instals",
    "instill": "instil",
    "instills": "instils",
    "institutionalization": "institutionalisation",
    "institutionalize": "institutionalise",
    "institutionalized": "institutionalised",
    "institutionalizes": "institutionalises",
    "institutionalizing": "institutionalising",
    "intellectualize": "intellectualise",
    "intellectualized": "intellectualised",
    "intellectualizes": "intellectualises",
    "intellectualizing": "intellectualising",
    "internalization": "internalisation",
    "internalize": "internalise",
    "internalized": "internalised",
    "internalizes": "internalises",
    "internalizing": "internalising",
    "internationalization": "internationalisation",
    "internationalize": "internationalise",
    "internationalized": "internationalised",
    "internationalizes": "internationalises",
    "internationalizing": "internationalising",
    "ionization": "ionisation",
    "ionize": "ionise",
    "ionized": "ionised",
    "ionizer": "ioniser",
    "ionizers": "ionisers",
    "ionizes": "ionises",
    "ionizing": "ionising",
    "italicize": "italicise",
    "italicized": "italicised",
    "italicizes": "italicises",
    "italicizing": "italicising",
    "itemize": "itemise",
    "itemized": "itemised",
    "itemizes": "itemises",
    "itemizing": "itemising",
    "jeopardize": "jeopardise",
    "jeopardized": "jeopardised",
    "jeopardizes": "jeopardises",
    "jeopardizing": "jeopardising",
    "jeweled": "jewelled",
    "jeweler": "jeweller",
    "jewelers": "jewellers",
    "jewelry": "jewellery",
    "judgment": "judgement",
    "kilogram": "kilogramme",
    "kilograms": "kilogrammes",
    "kilometer": "kilometre",
    "kilometers": "kilometres",
    "labeled": "labelled",
    "labeling": "labelling",
    "labor": "labour",
    "labored": "laboured",
    "laborer": "labourer",
    "laborers": "labourers",
    "laboring": "labouring",
    "labors": "labours",
    "lackluster": "lacklustre",
    "legalization": "legalisation",
    "legalize": "legalise",
    "legalized": "legalised",
    "legalizes": "legalises",
    "legalizing": "legalising",
    "legitimize": "legitimise",
    "legitimized": "legitimised",
    "legitimizes": "legitimises",
    "legitimizing": "legitimising",
    "leukemia": "leukaemia",
    "leveled": "levelled",
    "leveler": "leveller",
    "levelers": "levellers",
    "leveling": "levelling",
    "libeled": "libelled",
    "libeling": "libelling",
    "libelous": "libellous",
    "liberalization": "liberalisation",
    "liberalize": "liberalise",
    "liberalized": "liberalised",
    "liberalizes": "liberalises",
    "liberalizing": "liberalising",
    "license": "licence",
    "licensed": "licenced",
    "licenses": "licences",
    "licensing": "licencing",
    "likable": "likeable",
    "lionization": "lionisation",
    "lionize": "lionise",
    "lionized": "lionised",
    "lionizes": "lionises",
    "lionizing": "lionising",
    "liquidize": "liquidise",
    "liquidized": "liquidised",
    "liquidizer": "liquidiser",
    "liquidizers": "liquidisers",
    "liquidizes": "liquidises",
    "liquidizing": "liquidising",
    "liter": "litre",
    "liters": "litres",
    "localize": "localise",
    "localized": "localised",
    "localizes": "localises",
    "localizing": "localising",
    "louver": "louvre",
    "louvered": "louvred",
    "louvers": "louvres",
    "luster": "lustre",
    "magnetize": "magnetise",
    "magnetized": "magnetised",
    "magnetizes": "magnetises",
    "magnetizing": "magnetising",
    "maneuverability": "manoeuvrability",
    "maneuverable": "manoeuvrable",
    "maneuver": "manoeuvre",
    "maneuvered": "manoeuvred",
    "maneuvers": "manoeuvres",
    "maneuvering": "manoeuvring",
    "maneuverings": "manoeuvrings",
    "marginalization": "marginalisation",
    "marginalize": "marginalise",
    "marginalized": "marginalised",
    "marginalizes": "marginalises",
    "marginalizing": "marginalising",
    "marshaled": "marshalled",
    "marshaling": "marshalling",
    "marveled": "marvelled",
    "marveling": "marvelling",
    "marvelous": "marvellous",
    "marvelously": "marvellously",
    "materialization": "materialisation",
    "materialize": "materialise",
    "materialized": "materialised",
    "materializes": "materialises",
    "materializing": "materialising",
    "maximization": "maximisation",
    "maximize": "maximise",
    "maximized": "maximised",
    "maximizes": "maximises",
    "maximizing": "maximising",
    "meager": "meagre",
    "mechanization": "mechanisation",
    "mechanize": "mechanise",
    "mechanized": "mechanised",
    "mechanizes": "mechanises",
    "mechanizing": "mechanising",
    "medieval": "mediaeval",
    "memorialize": "memorialise",
    "memorialized": "memorialised",
    "memorializes": "memorialises",
    "memorializing": "memorialising",
    "memorize": "memorise",
    "memorized": "memorised",
    "memorizes": "memorises",
    "memorizing": "memorising",
    "mesmerize": "mesmerise",
    "mesmerized": "mesmerised",
    "mesmerizes": "mesmerises",
    "mesmerizing": "mesmerising",
    "metabolize": "metabolise",
    "metabolized": "metabolised",
    "metabolizes": "metabolises",
    "metabolizing": "metabolising",
    "meter": "metre",
    "meters": "metres",
    "micrometer": "micrometre",
    "micrometers": "micrometres",
    "militarize": "militarise",
    "militarized": "militarised",
    "militarizes": "militarises",
    "militarizing": "militarising",
    "milligram": "milligramme",
    "milligrams": "milligrammes",
    "milliliter": "millilitre",
    "milliliters": "millilitres",
    "millimeter": "millimetre",
    "millimeters": "millimetres",
    "miniaturization": "miniaturisation",
    "miniaturize": "miniaturise",
    "miniaturized": "miniaturised",
    "miniaturizes": "miniaturises",
    "miniaturizing": "miniaturising",
    "minibusses": "minibuses",
    "minimize": "minimise",
    "minimized": "minimised",
    "minimizes": "minimises",
    "minimizing": "minimising",
    "misbehavior": "misbehaviour",
    "misdemeanor": "misdemeanour",
    "misdemeanors": "misdemeanours",
    "misspelled": "misspelt",
    "miter": "mitre",
    "miters": "mitres",
    "mobilization": "mobilisation",
    "mobilize": "mobilise",
    "mobilized": "mobilised",
    "mobilizes": "mobilises",
    "mobilizing": "mobilising",
    "modeled": "modelled",
    "modeler": "modeller",
    "modelers": "modellers",
    "modeling": "modelling",
    "modernize": "modernise",
    "modernized": "modernised",
    "modernizes": "modernises",
    "modernizing": "modernising",
    "moisturize": "moisturise",
    "moisturized": "moisturised",
    "moisturizer": "moisturiser",
    "moisturizers": "moisturisers",
    "moisturizes": "moisturises",
    "moisturizing": "moisturising",
    "monolog": "monologue",
    "monologs": "monologues",
    "monopolization": "monopolisation",
    "monopolize": "monopolise",
    "monopolized": "monopolised",
    "monopolizes": "monopolises",
    "monopolizing": "monopolising",
    "moralize": "moralise",
    "moralized": "moralised",
    "moralizes": "moralises",
    "moralizing": "moralising",
    "motorized": "motorised",
    "mold": "mould",
    "molded": "moulded",
    "molder": "moulder",
    "moldered": "mouldered",
    "moldering": "mouldering",
    "molders": "moulders",
    "moldier": "mouldier",
    "moldiest": "mouldiest",
    "molding": "moulding",
    "moldings": "mouldings",
    "molds": "moulds",
    "moldy": "mouldy",
    "molt": "moult",
    "molted": "moulted",
    "molting": "moulting",
    "molts": "moults",
    "mustache": "moustache",
    "mustached": "moustached",
    "mustaches": "moustaches",
    "mustachioed": "moustachioed",
    "multicolored": "multicoloured",
    "nationalization": "nationalisation",
    "nationalizations": "nationalisations",
    "nationalize": "nationalise",
    "nationalized": "nationalised",
    "nationalizes": "nationalises",
    "nationalizing": "nationalising",
    "naturalization": "naturalisation",
    "naturalize": "naturalise",
    "naturalized": "naturalised",
    "naturalizes": "naturalises",
    "naturalizing": "naturalising",
    "neighbor": "neighbour",
    "neighborhood": "neighbourhood",
    "neighborhoods": "neighbourhoods",
    "neighboring": "neighbouring",
    "neighborliness": "neighbourliness",
    "neighborly": "neighbourly",
    "neighbors": "neighbours",
    "neutralization": "neutralisation",
    "neutralize": "neutralise",
    "neutralized": "neutralised",
    "neutralizes": "neutralises",
    "neutralizing": "neutralising",
    "normalization": "normalisation",
    "normalize": "normalise",
    "normalized": "normalised",
    "normalizes": "normalises",
    "normalizing": "normalising",
    "odor": "odour",
    "odorless": "odourless",
    "odors": "odours",
    "esophagus": "oesophagus",
    "esophaguses": "oesophaguses",
    "estrogen": "oestrogen",
    "offense": "offence",
    "offenses": "offences",
    "omelet": "omelette",
    "omelets": "omelettes",
    "optimize": "optimise",
    "optimized": "optimised",
    "optimizes": "optimises",
    "optimizing": "optimising",
    "organization": "organisation",
    "organizational": "organisational",
    "organizations": "organisations",
    "organize": "organise",
    "organized": "organised",
    "organizer": "organiser",
    "organizers": "organisers",
    "organizes": "organises",
    "organizing": "organising",
    "orthopedic": "orthopaedic",
    "orthopedics": "orthopaedics",
    "ostracize": "ostracise",
    "ostracized": "ostracised",
    "ostracizes": "ostracises",
    "ostracizing": "ostracising",
    "outmaneuver": "outmanoeuvre",
    "outmaneuvered": "outmanoeuvred",
    "outmaneuvers": "outmanoeuvres",
    "outmaneuvering": "outmanoeuvring",
    "overemphasize": "overemphasise",
    "overemphasized": "overemphasised",
    "overemphasizes": "overemphasises",
    "overemphasizing": "overemphasising",
    "oxidization": "oxidisation",
    "oxidize": "oxidise",
    "oxidized": "oxidised",
    "oxidizes": "oxidises",
    "oxidizing": "oxidising",
    "pederast": "paederast",
    "pederasts": "paederasts",
    "pediatric": "paediatric",
    "pediatrician": "paediatrician",
    "pediatricians": "paediatricians",
    "pediatrics": "paediatrics",
    "paleolithic": "palaeolithic",
    "paleontologist": "palaeontologist",
    "paleontologists": "palaeontologists",
    "paleontology": "palaeontology",
    "paneled": "panelled",
    "paneling": "panelling",
    "panelist": "panellist",
    "panelists": "panellists",
    "paralyze": "paralyse",
    "paralyzed": "paralysed",
    "paralyzes": "paralyses",
    "paralyzing": "paralysing",
    "parceled": "parcelled",
    "parceling": "parcelling",
    "parlor": "parlour",
    "parlors": "parlours",
    "particularize": "particularise",
    "particularized": "particularised",
    "particularizes": "particularises",
    "particularizing": "particularising",
    "passivization": "passivisation",
    "passivize": "passivise",
    "passivized": "passivised",
    "passivizes": "passivises",
    "passivizing": "passivising",
    "pasteurization": "pasteurisation",
    "pasteurize": "pasteurise",
    "pasteurized": "pasteurised",
    "pasteurizes": "pasteurises",
    "pasteurizing": "pasteurising",
    "patronize": "patronise",
    "patronized": "patronised",
    "patronizes": "patronises",
    "patronizing": "patronising",
    "patronizingly": "patronisingly",
    "pedaled": "pedalled",
    "pedaling": "pedalling",
    "pedestrianization": "pedestrianisation",
    "pedestrianize": "pedestrianise",
    "pedestrianized": "pedestrianised",
    "pedestrianizes": "pedestrianises",
    "pedestrianizing": "pedestrianising",
    "penalize": "penalise",
    "penalized": "penalised",
    "penalizes": "penalises",
    "penalizing": "penalising",
    "penciled": "pencilled",
    "penciling": "pencilling",
    "personalize": "personalise",
    "personalized": "personalised",
    "personalizes": "personalises",
    "personalizing": "personalising",
    "pharmacopeia": "pharmacopoeia",
    "pharmacopeias": "pharmacopoeias",
    "philosophize": "philosophise",
    "philosophized": "philosophised",
    "philosophizes": "philosophises",
    "philosophizing": "philosophising",
    "filter": "philtre",
    "filters": "philtres",
    "phony": "phoney",
    "plagiarize": "plagiarise",
    "plagiarized": "plagiarised",
    "plagiarizes": "plagiarises",
    "plagiarizing": "plagiarising",
    "plow": "plough",
    "plowed": "ploughed",
    "plowing": "ploughing",
    "plowman": "ploughman",
    "plowmen": "ploughmen",
    "plows": "ploughs",
    "plowshare": "ploughshare",
    "plowshares": "ploughshares",
    "polarization": "polarisation",
    "polarize": "polarise",
    "polarized": "polarised",
    "polarizes": "polarises",
    "polarizing": "polarising",
    "politicization": "politicisation",
    "politicize": "politicise",
    "politicized": "politicised",
    "politicizes": "politicises",
    "politicizing": "politicising",
    "popularization": "popularisation",
    "popularize": "popularise",
    "popularized": "popularised",
    "popularizes": "popularises",
    "popularizing": "popularising",
    "practice": "practise",
    "practiced": "practised",
    "practices": "practises",
    "practicing": "practising",
    "presidium": "praesidium",
    "presidiums": "praesidiums",
    "pressurization": "pressurisation",
    "pressurize": "pressurise",
    "pressurized": "pressurised",
    "pressurizes": "pressurises",
    "pressurizing": "pressurising",
    "pretense": "pretence",
    "pretenses": "pretences",
    "primeval": "primaeval",
    "prioritization": "prioritisation",
    "prioritize": "prioritise",
    "prioritized": "prioritised",
    "prioritizes": "prioritises",
    "prioritizing": "prioritising",
    "privatization": "privatisation",
    "privatizations": "privatisations",
    "privatize": "privatise",
    "privatized": "privatised",
    "privatizes": "privatises",
    "privatizing": "privatising",
    "professionalization": "professionalisation",
    "professionalize": "professionalise",
    "professionalized": "professionalised",
    "professionalizes": "professionalises",
    "professionalizing": "professionalising",
    "program": "programme",
    "programs": "programmes",
    "prolog": "prologue",
    "prologs": "prologues",
    "propagandize": "propagandise",
    "propagandized": "propagandised",
    "propagandizes": "propagandises",
    "propagandizing": "propagandising",
    "proselytize": "proselytise",
    "proselytized": "proselytised",
    "proselytizer": "proselytiser",
    "proselytizers": "proselytisers",
    "proselytizes": "proselytises",
    "proselytizing": "proselytising",
    "psychoanalyze": "psychoanalyse",
    "psychoanalyzed": "psychoanalysed",
    "psychoanalyzes": "psychoanalyses",
    "psychoanalyzing": "psychoanalysing",
    "publicize": "publicise",
    "publicized": "publicised",
    "publicizes": "publicises",
    "publicizing": "publicising",
    "pulverization": "pulverisation",
    "pulverize": "pulverise",
    "pulverized": "pulverised",
    "pulverizes": "pulverises",
    "pulverizing": "pulverising",
    "pummel": "pummelled",
    "pummeled": "pummelling",
    "pajama": "pyjama",
    "pajamas": "pyjamas",
    "pizzazz": "pzazz",
    "quarreled": "quarrelled",
    "quarreling": "quarrelling",
    "radicalize": "radicalise",
    "radicalized": "radicalised",
    "radicalizes": "radicalises",
    "radicalizing": "radicalising",
    "rancor": "rancour",
    "randomize": "randomise",
    "randomized": "randomised",
    "randomizes": "randomises",
    "randomizing": "randomising",
    "rationalization": "rationalisation",
    "rationalizations": "rationalisations",
    "rationalize": "rationalise",
    "rationalized": "rationalised",
    "rationalizes": "rationalises",
    "rationalizing": "rationalising",
    "raveled": "ravelled",
    "raveling": "ravelling",
    "realizable": "realisable",
    "realization": "realisation",
    "realizations": "realisations",
    "realize": "realise",
    "realized": "realised",
    "realizes": "realises",
    "realizing": "realising",
    "recognizable": "recognisable",
    "recognizably": "recognisably",
    "recognizance": "recognisance",
    "recognize": "recognise",
    "recognized": "recognised",
    "recognizes": "recognises",
    "recognizing": "recognising",
    "reconnoiter": "reconnoitre",
    "reconnoitered": "reconnoitred",
    "reconnoiters": "reconnoitres",
    "reconnoitering": "reconnoitring",
    "refueled": "refuelled",
    "refueling": "refuelling",
    "regularization": "regularisation",
    "regularize": "regularise",
    "regularized": "regularised",
    "regularizes": "regularises",
    "regularizing": "regularising",
    "remodeled": "remodelled",
    "remodeling": "remodelling",
    "remold": "remould",
    "remolded": "remoulded",
    "remolding": "remoulding",
    "remolds": "remoulds",
    "reorganization": "reorganisation",
    "reorganizations": "reorganisations",
    "reorganize": "reorganise",
    "reorganized": "reorganised",
    "reorganizes": "reorganises",
    "reorganizing": "reorganising",
    "reveled": "revelled",
    "reveler": "reveller",
    "revelers": "revellers",
    "reveling": "revelling",
    "revitalize": "revitalise",
    "revitalized": "revitalised",
    "revitalizes": "revitalises",
    "revitalizing": "revitalising",
    "revolutionize": "revolutionise",
    "revolutionized": "revolutionised",
    "revolutionizes": "revolutionises",
    "revolutionizing": "revolutionising",
    "rhapsodize": "rhapsodise",
    "rhapsodized": "rhapsodised",
    "rhapsodizes": "rhapsodises",
    "rhapsodizing": "rhapsodising",
    "rigor": "rigour",
    "rigors": "rigours",
    "ritualized": "ritualised",
    "rivaled": "rivalled",
    "rivaling": "rivalling",
    "romanticize": "romanticise",
    "romanticized": "romanticised",
    "romanticizes": "romanticises",
    "romanticizing": "romanticising",
    "rumor": "rumour",
    "rumored": "rumoured",
    "rumors": "rumours",
    "saber": "sabre",
    "sabers": "sabres",
    "saltpeter": "saltpetre",
    "sanitize": "sanitise",
    "sanitized": "sanitised",
    "sanitizes": "sanitises",
    "sanitizing": "sanitising",
    "satirize": "satirise",
    "satirized": "satirised",
    "satirizes": "satirises",
    "satirizing": "satirising",
    "savior": "saviour",
    "saviors": "saviours",
    "savor": "savour",
    "savored": "savoured",
    "savories": "savouries",
    "savoring": "savouring",
    "savors": "savours",
    "savory": "savoury",
    "scandalize": "scandalise",
    "scandalized": "scandalised",
    "scandalizes": "scandalises",
    "scandalizing": "scandalising",
    "skeptic": "sceptic",
    "skeptical": "sceptical",
    "skeptically": "sceptically",
    "skepticism": "scepticism",
    "skeptics": "sceptics",
    "scepter": "sceptre",
    "scepters": "sceptres",
    "scrutinize": "scrutinise",
    "scrutinized": "scrutinised",
    "scrutinizes": "scrutinises",
    "scrutinizing": "scrutinising",
    "secularization": "secularisation",
    "secularize": "secularise",
    "secularized": "secularised",
    "secularizes": "secularises",
    "secularizing": "secularising",
    "sensationalize": "sensationalise",
    "sensationalized": "sensationalised",
    "sensationalizes": "sensationalises",
    "sensationalizing": "sensationalising",
    "sensitize": "sensitise",
    "sensitized": "sensitised",
    "sensitizes": "sensitises",
    "sensitizing": "sensitising",
    "sentimentalize": "sentimentalise",
    "sentimentalized": "sentimentalised",
    "sentimentalizes": "sentimentalises",
    "sentimentalizing": "sentimentalising",
    "sepulcher": "sepulchre",
    "sepulchers": "sepulchres",
    "serialization": "serialisation",
    "serializations": "serialisations",
    "serialize": "serialise",
    "serialized": "serialised",
    "serializes": "serialises",
    "serializing": "serialising",
    "sermonize": "sermonise",
    "sermonized": "sermonised",
    "sermonizes": "sermonises",
    "sermonizing": "sermonising",
    "sheik": "sheikh",
    "shoveled": "shovelled",
    "shoveling": "shovelling",
    "shriveled": "shrivelled",
    "shriveling": "shrivelling",
    "signalize": "signalise",
    "signalized": "signalised",
    "signalizes": "signalises",
    "signalizing": "signalising",
    "signaled": "signalled",
    "signaling": "signalling",
    "smolder": "smoulder",
    "smoldered": "smouldered",
    "smoldering": "smouldering",
    "smolders": "smoulders",
    "sniveled": "snivelled",
    "sniveling": "snivelling",
    "snorkeled": "snorkelled",
    "snorkeling": "snorkelling",
    "snowplow": "snowploughs",
    "socialization": "socialisation",
    "socialize": "socialise",
    "socialized": "socialised",
    "socializes": "socialises",
    "socializing": "socialising",
    "solemnize": "solemnise",
    "solemnized": "solemnised",
    "solemnizes": "solemnises",
    "solemnizing": "solemnising",
    "somber": "sombre",
    "specialization": "specialisation",
    "specializations": "specialisations",
    "specialize": "specialise",
    "specialized": "specialised",
    "specializes": "specialises",
    "specializing": "specialising",
    "specter": "spectre",
    "specters": "spectres",
    "spiraled": "spiralled",
    "spiraling": "spiralling",
    "splendor": "splendour",
    "splendors": "splendours",
    "squirreled": "squirrelled",
    "squirreling": "squirrelling",
    "stabilization": "stabilisation",
    "stabilize": "stabilise",
    "stabilized": "stabilised",
    "stabilizer": "stabiliser",
    "stabilizers": "stabilisers",
    "stabilizes": "stabilises",
    "stabilizing": "stabilising",
    "standardization": "standardisation",
    "standardize": "standardise",
    "standardized": "standardised",
    "standardizes": "standardises",
    "standardizing": "standardising",
    "stenciled": "stencilled",
    "stenciling": "stencilling",
    "sterilization": "sterilisation",
    "sterilizations": "sterilisations",
    "sterilize": "sterilise",
    "sterilized": "sterilised",
    "sterilizer": "steriliser",
    "sterilizers": "sterilisers",
    "sterilizes": "sterilises",
    "sterilizing": "sterilising",
    "stigmatization": "stigmatisation",
    "stigmatize": "stigmatise",
    "stigmatized": "stigmatised",
    "stigmatizes": "stigmatises",
    "stigmatizing": "stigmatising",
    "story": "storey",
    "stories": "storeys",
    "subsidization": "subsidisation",
    "subsidize": "subsidise",
    "subsidized": "subsidised",
    "subsidizer": "subsidiser",
    "subsidizers": "subsidisers",
    "subsidizes": "subsidises",
    "subsidizing": "subsidising",
    "succor": "succour",
    "succored": "succoured",
    "succoring": "succouring",
    "succors": "succours",
    "sulfate": "sulphate",
    "sulfates": "sulphates",
    "sulfide": "sulphide",
    "sulfides": "sulphides",
    "sulfur": "sulphur",
    "sulfurous": "sulphurous",
    "summarize": "summarise",
    "summarized": "summarised",
    "summarizes": "summarises",
    "summarizing": "summarising",
    "swiveled": "swivelled",
    "swiveling": "swivelling",
    "symbolize": "symbolise",
    "symbolized": "symbolised",
    "symbolizes": "symbolises",
    "symbolizing": "symbolising",
    "sympathize": "sympathise",
    "sympathized": "sympathised",
    "sympathizer": "sympathiser",
    "sympathizers": "sympathisers",
    "sympathizes": "sympathises",
    "sympathizing": "sympathising",
    "synchronization": "synchronisation",
    "synchronize": "synchronise",
    "synchronized": "synchronised",
    "synchronizes": "synchronises",
    "synchronizing": "synchronising",
    "synthesize": "synthesise",
    "synthesized": "synthesised",
    "synthesizer": "synthesiser",
    "synthesizers": "synthesisers",
    "synthesizes": "synthesises",
    "synthesizing": "synthesising",
    "siphon": "syphon",
    "siphoned": "syphoned",
    "siphoning": "syphoning",
    "siphons": "syphons",
    "systematization": "systematisation",
    "systematize": "systematise",
    "systematized": "systematised",
    "systematizes": "systematises",
    "systematizing": "systematising",
    "tantalize": "tantalise",
    "tantalized": "tantalised",
    "tantalizes": "tantalises",
    "tantalizing": "tantalising",
    "tantalizingly": "tantalisingly",
    "tasseled": "tasselled",
    "technicolor": "technicolour",
    "temporize": "temporise",
    "temporized": "temporised",
    "temporizes": "temporises",
    "temporizing": "temporising",
    "tenderize": "tenderise",
    "tenderized": "tenderised",
    "tenderizes": "tenderises",
    "tenderizing": "tenderising",
    "terrorize": "terrorise",
    "terrorized": "terrorised",
    "terrorizes": "terrorises",
    "terrorizing": "terrorising",
    "theater": "theatre",
    "theatergoer": "theatregoer",
    "theatergoers": "theatregoers",
    "theaters": "theatres",
    "theorize": "theorise",
    "theorized": "theorised",
    "theorizes": "theorises",
    "theorizing": "theorising",
    "ton": "tonne",
    "tons": "tonnes",
    "toweled": "towelled",
    "toweling": "towelling",
    "toxemia": "toxaemia",
    "tranquilize": "tranquillize",
    "tranquilized": "tranquillized",
    "tranquilizer": "tranquillizer",
    "tranquilizers": "tranquillizers",
    "tranquilizes": "tranquillizes",
    "tranquilizing": "tranquillizing",
    "tranquility": "tranquilly",
    "transistorized": "transistorised",
    "traumatize": "traumatise",
    "traumatized": "traumatised",
    "traumatizes": "traumatises",
    "traumatizing": "traumatising",
    "traveled": "travelled",
    "traveler": "traveller",
    "travelers": "travellers",
    "traveling": "travelling",
    "travelog": "travelogue",
    "travelogs": "travelogues",
    "trialed": "trialled",
    "trialing": "trialling",
    "tricolor": "tricolour",
    "tricolors": "tricolours",
    "trivialize": "trivialise",
    "trivialized": "trivialised",
    "trivializes": "trivialises",
    "trivializing": "trivialising",
    "tumor": "tumour",
    "tumors": "tumours",
    "tunneled": "tunnelled",
    "tunneling": "tunnelling",
    "tyrannize": "tyrannise",
    "tyrannized": "tyrannised",
    "tyrannizes": "tyrannises",
    "tyrannizing": "tyrannising",
    "tire": "tyre",
    "tires": "tyres",
    "unauthorized": "unauthorised",
    "uncivilized": "uncivilised",
    "underutilized": "underutilised",
    "unequaled": "unequalled",
    "unfavorable": "unfavourable",
    "unfavorably": "unfavourably",
    "unionization": "unionisation",
    "unionize": "unionise",
    "unionized": "unionised",
    "unionizes": "unionises",
    "unionizing": "unionising",
    "unorganized": "unorganised",
    "unraveled": "unravelled",
    "unraveling": "unravelling",
    "unrecognizable": "unrecognisable",
    "unrecognized": "unrecognised",
    "unrivaled": "unrivalled",
    "unsavory": "unsavoury",
    "untrammeled": "untrammelled",
    "urbanization": "urbanisation",
    "urbanize": "urbanise",
    "urbanized": "urbanised",
    "urbanizes": "urbanises",
    "urbanizing": "urbanising",
    "utilizable": "utilisable",
    "utilization": "utilisation",
    "utilize": "utilise",
    "utilized": "utilised",
    "utilizes": "utilises",
    "utilizing": "utilising",
    "valor": "valour",
    "vandalize": "vandalise",
    "vandalized": "vandalised",
    "vandalizes": "vandalises",
    "vandalizing": "vandalising",
    "vaporization": "vaporisation",
    "vaporize": "vaporise",
    "vaporized": "vaporised",
    "vaporizes": "vaporises",
    "vaporizing": "vaporising",
    "vapor": "vapour",
    "vapors": "vapours",
    "verbalize": "verbalise",
    "verbalized": "verbalised",
    "verbalizes": "verbalises",
    "verbalizing": "verbalising",
    "victimization": "victimisation",
    "victimize": "victimise",
    "victimized": "victimised",
    "victimizes": "victimises",
    "victimizing": "victimising",
    "videodisk": "videodisc",
    "videodisks": "videodiscs",
    "vigor": "vigour",
    "visualization": "visualisation",
    "visualizations": "visualisations",
    "visualize": "visualise",
    "visualized": "visualised",
    "visualizes": "visualises",
    "visualizing": "visualising",
    "vocalization": "vocalisation",
    "vocalizations": "vocalisations",
    "vocalize": "vocalise",
    "vocalized": "vocalised",
    "vocalizes": "vocalises",
    "vocalizing": "vocalising",
    "vulcanized": "vulcanised",
    "vulgarization": "vulgarisation",
    "vulgarize": "vulgarise",
    "vulgarized": "vulgarised",
    "vulgarizes": "vulgarises",
    "vulgarizing": "vulgarising",
    "wagon": "waggon",
    "wagons": "waggons",
    "watercolor": "watercolour",
    "watercolors": "watercolours",
    "weaseled": "weaselled",
    "weaseling": "weaselling",
    "westernization": "westernisation",
    "westernize": "westernise",
    "westernized": "westernised",
    "westernizes": "westernises",
    "westernizing": "westernising",
    "womanize": "womanise",
    "womanized": "womanised",
    "womanizer": "womaniser",
    "womanizers": "womanisers",
    "womanizes": "womanises",
    "womanizing": "womanising",
    "woolen": "woollen",
    "woolens": "woollens",
    "woolies": "woollies",
    "wooly": "woolly",
    "worshiped": "worshipped",
    "worshiping": "worshipping",
    "worshiper": "worshipper",
    "yodeled": "yodelled",
    "yodeling": "yodelling",
    "yogurt": "yoghurt",
    "yogurts": "yoghurts"
}

const americanToBritishTitles = {
    'mr.': 'mr',
    'mrs.': 'mrs',
    'ms.': 'ms',
    'mx.': 'mx',
    'dr.': 'dr',
    'prof.': 'prof',
    'Mr.': 'Mr',
    'Mrs.': 'Mrs',
    'Ms.': 'Ms',
    'Mx.': 'Mx',
    'Dr.': 'Dr',
    'Prof.': 'Prof'
}

const britishOnly = {
    "abseil": "rappel",
    "accountancy": "accounting",
    "advert": "advertisement",
    "agony column": "advice column",
    "answerphone": "answering machine",
    "anti-clockwise": "counterclockwise",
    "approved school": "juvie",
    "artic": "semi",
    "athletics meeting": "track meet",
    "aubergine": "eggplant",
    "autocue": "teleprompter",
    "bank holiday": "public holiday",
    "barmy": "balmy",
    "biccie": "cookie",
    "bicky": "cookie",
    "bikky": "cookie",
    "biro": "ballpoint pen",
    "bits and bobs": "odds and ends",
    "black pudding": "blood sausage",
    "bloke": "guy",
    "blower": "telephone",
    "boffin": "an expert",
    "bog roll": "roll of toilet paper",
    "bog-standard": "garden-variety",
    "boiled sweet": "hard candy",
    "bone-idle": "lazy",
    "brekkie": "breakfast",
    "brekky": "breakfast",
    "breve": "double whole note",
    "brolly": "umbrella",
    "building society": "savings and loan association",
    "bum bag": "fanny pack",
    "bunce": "a windfall",
    "bureau de change": "currency exchange",
    "burgle": "burglarize",
    "by-election": "special election",
    "cafetière": "French press",
    "cafetiere": "French press",
    "caff": "café",
    "cagoule": "windbreaker",
    "candidature": "candidacy",
    "candy floss": "cotton candy",
    "car boot sale": "swap meet",
    "car boot": "trunk",
    "car hire": "car rental",
    "car park": "parking lot",
    "carer": "caregiver",
    "carriageway": "lane",
    "cash machine": "ATM",
    "cashpoint": "ATM",
    "central reservation": "median strip",
    "chancer": "opportunist",
    "chat up": "flirt",
    "chatted up": "flirted",
    "cheeky": "impertinent",
    "child-minder": "babysitter",
    "chinwag": "chat",
    "chippy": "fish-and-chip shop",
    "chip shop": "fish-and-chip shop",
    "chuffed": "pleased",
    "chunder": "vomit",
    "clapped out": "clapped out",
    "cleg": "horse fly",
    "clingfilm": "plastic wrap",
    "cling-film": "plastic wrap",
    "cling film": "plastic wrap",
    "cobblers": "shoe repairers",
    "conservatoire": "conservatory",
    "cotton bud": "cotton swab",
    "cotton wool": "cotton ball",
    "counterfoil": "stub",
    "counterpane": "bedspread",
    "courgette": "zucchini",
    "crisps": "potato chips",
    "cuppa": "cup of tea",
    "current account": "checking account",
    "daft": "silly",
    "dogsbody": "grunt",
    "dosh": "dough",
    "double first": "undergraduate degree",
    "draper": "dry goods",
    "draughts": "checkers",
    "drawing pin": "thumbtack",
    "drink-driving": "drunk driving",
    "driving licence": "driver's license",
    "dual carriageway": "divided highway",
    "dustbin": "trash can",
    "dustman": "garbage man",
    "dustbin man": "garbage man",
    "dustcart": "garbage truck",
    "earthed": "grounded",
    "elastoplast": "bandage",
    "electric fire": "space heater",
    "engaged tone": "busy signal",
    "estate agent": "real estate agent",
    "estate car": "station wagon",
    "extension lead": "extension cord",
    "fancy a": "would you like a",
    "fairy cake": "cupcake",
    "fairy lights": "Christmas lights",
    "fire brigade": "fire department",
    "flight lieutenant": "captain",
    "flypast": "flyby",
    "footie": "soccer",
    "freephone": "toll-free number",
    "funfair": "carnival",
    "gaol": "jail",
    "gherkin": "pickle",
    "group captain": "colonel",
    "guard's van": "caboose",
    "guv": "governor",
    "heath robinson device": "rube goldberg device",
    "high street": "main street",
    "hire purchase": "installment plan",
    "hold-all": "duffel bag",
    "holidaymaker": "vacationer",
    "hols": "holidays",
    "hot up": "heating up",
    "ice lolly": "popsicle",
    "identity parade": "police lineup",
    "inverted commas": "quotation marks",
    "invigilator": "proctor",
    "ironmongery": "hardware store",
    "jacket potato": "baked potato",
    "jemmy": "jimmy",
    "jerrybuilt": "jerry-rigged",
    "jerry-built": "jerry-rigged",
    "jumble sale": "rummage sale",
    "jump leads": "jumper cables",
    "kirby grip": "bobby pin",
    "kitchen roll": "paper towels",
    "knacker's yard": "junkyard",
    "ladybird": "ladybug",
    "launderette": "laundromat",
    "lav": "toilet",
    "learnt": "learned",
    "loo": "bathroom",
    "lorry": "truck",
    "loudhailer": "megaphone",
    "maths": "math",
    "mole grips": "vise-grips",
    "motorway": "freeway",
    "muppet": "an incompetent or foolish person",
    "nark": "narc",
    "nappy": "daiper",
    "nosy parker": "nosy",
    "nosey parker": "nosy",
    "number plate": "license plate",
    "oap": "senior citizen",
    "off-licence": "liquor store",
    "offie": "liquor store",
    "off-the-peg": "off-the-rack",
    "oughtn't": "shouldn't",
    "overleaf": "reverse",
    "owt": "anything",
    "pants": "underwear",
    "panda car": "police car",
    "paper round": "paper route",
    "paracetamol": "Tylenol",
    "pernickety": "persnickety",
    "petrol": "gasoline",
    "petrolhead": "gearhead",
    "phone box": "payphone",
    "pillar box": "mailbox",
    "pillar-box red": "fire engine red",
    "plasterboard": "drywall",
    "plectrum": "guitar pick",
    "postal order": "money order",
    "poste restante": "general delivery",
    "postie": "postman",
    "pound shop": "dollar store",
    "pram": "stroller",
    "perambulator": "stroller",
    "prang": "fender bender",
    "prat": "idiot",
    "press-up": "push-up",
    "press-ups": "push-ups",
    "pritt-stick": "glue stick",
    "provisional licence": "learner's permit",
    "provisional driving licence": "learner's permit",
    "pub": "bar",
    "publican": "landlord",
    "punch-up": "a fistfight",
    "pushchair": "stroller",
    "quieten down": "quiet down",
    "rashers": "bacon",
    "recce": "recon",
    "reel of cotton": "spool of thread",
    "sarky": "snarky",
    "sarnie": "sandwich",
    "sarny": "sandwich",
    "sannie": "sandwich",
    "sat nav": "GPS",
    "self-raising flour": "self-rising flour",
    "selling-out shop": "liquor store",
    "sellotape": "Scotch tape",
    "shan't": "won't",
    "shopping trolley": "shopping cart",
    "skint": "broke",
    "skirting board": "baseboard",
    "slaphead": "bald man",
    "sleeping partner": "silent partner",
    "sleeping policeman": "speed bump",
    "slippy": "slippery",
    "slowcoach": "slowpoke",
    "smart dress": "formal attire",
    "snog": "kiss",
    "spawny": "lucky",
    "spiffing": "spiffy",
    "spot of tea": "cup of tea",
    "squaddie": "grunt",
    "squidgy": "squishy",
    "stockist": "dealer",
    "sun cream": "sunscreen",
    "suspender belt": "garter belt",
    "swimming costume": "swimsuit",
    "ta": "thank you",
    "takeaway": "takeout",
    "tannoy": "public address system",
    "tea towel": "dish towel",
    "telephone kiosk": "phone booth",
    "telly": "television",
    "ticket tout": "scalper",
    "tipp-ex": "Wite-Out",
    "tipping down": "raining hard",
    "trainers": "sneakers",
    "transport cafe": "truckstop",
    "trousers": "pants",
    "truncheon": "nightstick",
    "turf accountant": "bookie",
    "turn-indicator": "turn signal",
    "turn-ups": "cuffs",
    "twee": "cutesy",
    "uni": "college",
    "upmarket": "upscale",
    "veg": "vegetables",
    "wage packet": "paycheck",
    "washing-up liquid": "dish soap",
    "wc": "bathroom",
    "windscreen": "windshield",
    "wing mirrors": "side mirrors",
    "y-fronts": "briefs",
    "zebra crossing": "crosswalk"
}
  

console.log("hi")

clearButton.addEventListener('click', () => {
  outputDiv.innerHTML = "";
  textBox.value = "";
  console.log("Cleared")
  
});

translateButton.addEventListener('click', () => {
  if (!textBox.value) return (errorDiv.innerHTML = "<span color='red'>Error: No text to translate.</span>");
  let initialInput = textBox.value
  let inputString = textBox.value 
  if (locale.value == "american-to-british") {
    //to do: handle time
    inputString = inputString.replace(/(?<=\d\d):(?=\d\d)/, `<span class="highlight">.</span>`)
    for (const americanPhrase in americanOnly) {
      let regObj = new RegExp(americanPhrase,"gi")
      //console.log(regObj)
      inputString = inputString.replace(regObj, `<span class="highlight">${americanOnly[americanPhrase]}</span>`)
    }
    for (const americanWord in americanToBritishSpelling) {
      let regObj = new RegExp(americanWord,"gi")
      inputString = inputString.replace(regObj, `<span class="highlight">${americanToBritishSpelling[americanWord]}</span>`)
    }
    for (const americanTitles in americanToBritishTitles) {
      let regObj = new RegExp(americanTitles,"gi")
      inputString = inputString.replace(regObj, `<span class="highlight">${americanToBritishTitles[americanTitles]}</span>`)
    }
    for (const britishPhrase in britishOnly) {
      let regObj = new RegExp(britishOnly[britishPhrase],"gi")
      inputString = inputString.replace(regObj, `<span class="highlight">${britishPhrase}</span>`)
    }

  }
  else if (locale.value == "british-to-american") {
    inputString = inputString.replace(/(?<=\d\d)\.(?=\d\d)/, `<span class="highlight">:</span>`)
    for (const britishPhrase in britishOnly) {
      let regObj = new RegExp(britishPhrase,"gi")
      inputString = inputString.replace(regObj, `<span class="highlight">${britishOnly[britishPhrase]}</span>`)
    }
    for (const americanPhrase in americanOnly) {
      let regObj = new RegExp(americanOnly[americanPhrase],"gi")
      //console.log(regObj)
      inputString = inputString.replace(regObj, `<span class="highlight">${americanPhrase}</span>`)
    }
    for (const americanWord in americanToBritishSpelling) {
      let regObj = new RegExp(americanToBritishSpelling[americanWord],"gi")
      inputString = inputString.replace(regObj, `<span class="highlight">${americanWord}</span>`)
    }
    for (const americanTitles in americanToBritishTitles) {
      let regObj = new RegExp(americanToBritishTitles[americanTitles],"gi")
      inputString = inputString.replace(regObj, `<span class="highlight">${americanTitles}</span>`)
    }

  }

  if (initialInput == inputString) {
    inputString = "Everything looks good to me!"
  }
  outputDiv.innerHTML = inputString

});


try {
    module.exports = {
  
    }
  } catch (e) {}
  
*/